export const watchList = [
    {
        "scripOrder": 1,
        "marketCap": "144146.22",
        "tradeSymbol": "COALINDIA-EQ",
        "isCashWithFno": true,
        "nseCashToken": "20374",
        "bseCashToken": "533278",
        "curFutToken": "",
        "astCls": "cash",
        "details": "COAL INDIA LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "48550",
        "instName": "",
        "isinCode": "INE522F01014",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "39730",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "COAL INDIA LTD",
        "series": "EQ",
        "stockID": "421555",
        "strkPrice": "-1",
        "symbolName": "COALINDIA",
        "token": "20374",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "221858",
        "sector": "Mining & Mineral products",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 2,
        "marketCap": "130762.67",
        "tradeSymbol": "IOC-EQ",
        "isCashWithFno": true,
        "nseCashToken": "1624",
        "bseCashToken": "530965",
        "curFutToken": "",
        "astCls": "cash",
        "details": "INDIAN OIL CORP LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "19055",
        "instName": "",
        "isinCode": "INE242A01010",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "15595",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "INDIAN OIL CORP LTD",
        "series": "EQ",
        "stockID": "901145",
        "strkPrice": "-1",
        "symbolName": "IOC",
        "token": "1624",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "564849",
        "sector": "Refineries",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 7,
        "marketCap": "223928.97",
        "tradeSymbol": "ONGC-EQ",
        "isCashWithFno": true,
        "nseCashToken": "2475",
        "bseCashToken": "500312",
        "curFutToken": "",
        "astCls": "cash",
        "details": "OIL AND NATURAL GAS CORP.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "29625",
        "instName": "",
        "isinCode": "INE213A01029",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "24245",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "OIL AND NATURAL GAS CORP.",
        "series": "EQ",
        "stockID": "640830",
        "strkPrice": "-1",
        "symbolName": "ONGC",
        "token": "2475",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "364828",
        "sector": "Crude Oil & Natural Gas",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 8,
        "marketCap": "206538.99",
        "tradeSymbol": "NTPC-EQ",
        "isCashWithFno": true,
        "nseCashToken": "11630",
        "bseCashToken": "532555",
        "curFutToken": "",
        "astCls": "cash",
        "details": "NTPC LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "36970",
        "instName": "",
        "isinCode": "INE733E01010",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "30250",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "NTPC LTD",
        "series": "EQ",
        "stockID": "166797",
        "strkPrice": "-1",
        "symbolName": "NTPC",
        "token": "11630",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "290899",
        "sector": "Power Generation & Distribution",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 9,
        "marketCap": "170549.82",
        "tradeSymbol": "POWERGRID-EQ",
        "isCashWithFno": true,
        "nseCashToken": "14977",
        "bseCashToken": "532898",
        "curFutToken": "",
        "astCls": "cash",
        "details": "POWER GRID CORP. LTD.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "32175",
        "instName": "",
        "isinCode": "INE752E01010",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "26325",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "POWER GRID CORP. LTD.",
        "series": "EQ",
        "stockID": "417663",
        "strkPrice": "-1",
        "symbolName": "POWERGRID",
        "token": "14977",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "334821",
        "sector": "Power Generation & Distribution",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 10,
        "marketCap": "559920.59",
        "tradeSymbol": "ITC-EQ",
        "isCashWithFno": true,
        "nseCashToken": "1660",
        "bseCashToken": "500875",
        "curFutToken": "",
        "astCls": "cash",
        "details": "ITC LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "45225",
        "instName": "",
        "isinCode": "INE154A01025",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "37005",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "ITC LTD",
        "series": "EQ",
        "stockID": "397071",
        "strkPrice": "-1",
        "symbolName": "ITC",
        "token": "1660",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "237036",
        "sector": "Tobacco Products",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 11,
        "marketCap": "227898.01",
        "tradeSymbol": "WIPRO-EQ",
        "isCashWithFno": true,
        "nseCashToken": "3787",
        "bseCashToken": "507685",
        "curFutToken": "",
        "astCls": "cash",
        "details": "WIPRO LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "58455",
        "instName": "",
        "isinCode": "INE075A01022",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "47830",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "WIPRO LTD",
        "series": "EQ",
        "stockID": "531139",
        "strkPrice": "-1",
        "symbolName": "WIPRO",
        "token": "3787",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "188072",
        "sector": "IT - Software",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 12,
        "marketCap": "500492.24",
        "tradeSymbol": "SBIN-EQ",
        "isCashWithFno": true,
        "nseCashToken": "3045",
        "bseCashToken": "500112",
        "curFutToken": "",
        "astCls": "cash",
        "details": "STATE BANK OF INDIA",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "82480",
        "instName": "",
        "isinCode": "INE062A01020",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "67490",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "STATE BANK OF INDIA",
        "series": "EQ",
        "stockID": "347516",
        "strkPrice": "-1",
        "symbolName": "SBIN",
        "token": "3045",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "124944",
        "sector": "Banks",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 13,
        "marketCap": "193244.69",
        "tradeSymbol": "JSWSTEEL-EQ",
        "isCashWithFno": true,
        "nseCashToken": "11723",
        "bseCashToken": "500228",
        "curFutToken": "",
        "astCls": "cash",
        "details": "JSW STEEL LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "90080",
        "instName": "",
        "isinCode": "INE019A01038",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "73705",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "JSW STEEL LIMITED",
        "series": "EQ",
        "stockID": "891577",
        "strkPrice": "-1",
        "symbolName": "JSWSTEEL",
        "token": "11723",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "119827",
        "sector": "Steel",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 14,
        "marketCap": "502942.75",
        "tradeSymbol": "BHARTIARTL-EQ",
        "isCashWithFno": true,
        "nseCashToken": "10604",
        "bseCashToken": "532454",
        "curFutToken": "",
        "astCls": "cash",
        "details": "BHARTI AIRTEL LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "124025",
        "instName": "",
        "isinCode": "INE397D01024",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "101475",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "BHARTI AIRTEL LIMITED",
        "series": "EQ",
        "stockID": "468567",
        "strkPrice": "-1",
        "symbolName": "BHARTIARTL",
        "token": "10604",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "84326",
        "sector": "Telecomm-Service",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 15,
        "marketCap": "170035.34",
        "tradeSymbol": "ADANIPORTS-EQ",
        "isCashWithFno": true,
        "nseCashToken": "15083",
        "bseCashToken": "532921",
        "curFutToken": "",
        "astCls": "cash",
        "details": "ADANI PORT & SEZ LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "146235",
        "instName": "",
        "isinCode": "INE742F01042",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "119650",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "ADANI PORT & SEZ LTD",
        "series": "EQ",
        "stockID": "716033",
        "strkPrice": "-1",
        "symbolName": "ADANIPORTS",
        "token": "15083",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "73444",
        "sector": "Marine Port & Services",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 16,
        "marketCap": "671569.79",
        "tradeSymbol": "ICICIBANK-EQ",
        "isCashWithFno": true,
        "nseCashToken": "4963",
        "bseCashToken": "532174",
        "curFutToken": "",
        "astCls": "cash",
        "details": "ICICI BANK LTD.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "116620",
        "instName": "",
        "isinCode": "INE090A01021",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "95420",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "ICICI BANK LTD.",
        "series": "EQ",
        "stockID": "478299",
        "strkPrice": "-1",
        "symbolName": "ICICIBANK",
        "token": "4963",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "91183",
        "sector": "Banks",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 17,
        "marketCap": "289523.37",
        "tradeSymbol": "AXISBANK-EQ",
        "isCashWithFno": true,
        "nseCashToken": "5900",
        "bseCashToken": "532215",
        "curFutToken": "",
        "astCls": "cash",
        "details": "AXIS BANK LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "118695",
        "instName": "",
        "isinCode": "INE238A01034",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "97115",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "AXIS BANK LIMITED",
        "series": "EQ",
        "stockID": "112501",
        "strkPrice": "-1",
        "symbolName": "AXISBANK",
        "token": "5900",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "92510",
        "sector": "Banks",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 18,
        "marketCap": "272144.57",
        "tradeSymbol": "SUNPHARMA-EQ",
        "isCashWithFno": true,
        "nseCashToken": "3351",
        "bseCashToken": "524715",
        "curFutToken": "",
        "astCls": "cash",
        "details": "SUN PHARMACEUTICAL IND L",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "174100",
        "instName": "",
        "isinCode": "INE044A01036",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "142450",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "SUN PHARMACEUTICAL IND L",
        "series": "EQ",
        "stockID": "948699",
        "strkPrice": "-1",
        "symbolName": "SUNPHARMA",
        "token": "3351",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "62382",
        "sector": "Pharmaceuticals",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 19,
        "marketCap": "317770.18",
        "tradeSymbol": "HCLTECH-EQ",
        "isCashWithFno": true,
        "nseCashToken": "7229",
        "bseCashToken": "532281",
        "curFutToken": "",
        "astCls": "cash",
        "details": "HCL TECHNOLOGIES LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "182465",
        "instName": "",
        "isinCode": "INE860A01027",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "149295",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "HCL TECHNOLOGIES LTD",
        "series": "EQ",
        "stockID": "308453",
        "strkPrice": "-1",
        "symbolName": "HCLTECH",
        "token": "7229",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "59700",
        "sector": "IT - Software",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 20,
        "marketCap": "192355.26",
        "tradeSymbol": "M&M-EQ",
        "isCashWithFno": true,
        "nseCashToken": "2031",
        "bseCashToken": "500520",
        "curFutToken": "",
        "astCls": "cash",
        "details": "MAHINDRA & MAHINDRA LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "214565",
        "instName": "",
        "isinCode": "INE101A01026",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "175555",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "MAHINDRA & MAHINDRA LTD",
        "series": "EQ",
        "stockID": "845805",
        "strkPrice": "-1",
        "symbolName": "M&M",
        "token": "2031",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "50984",
        "sector": "Automobile",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 21,
        "marketCap": "578350.06",
        "tradeSymbol": "INFY-EQ",
        "isCashWithFno": true,
        "nseCashToken": "1594",
        "bseCashToken": "500209",
        "curFutToken": "",
        "astCls": "cash",
        "details": "INFOSYS LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "182995",
        "instName": "",
        "isinCode": "INE009A01021",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "149725",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "INFOSYS LIMITED",
        "series": "EQ",
        "stockID": "399834",
        "strkPrice": "-1",
        "symbolName": "INFY",
        "token": "1594",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "58106",
        "sector": "IT - Software",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 22,
        "marketCap": "236459.42",
        "tradeSymbol": "BAJAJFINSV-EQ",
        "isCashWithFno": true,
        "nseCashToken": "16675",
        "bseCashToken": "532978",
        "curFutToken": "",
        "astCls": "cash",
        "details": "BAJAJ FINSERV LTD.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "176065",
        "instName": "",
        "isinCode": "INE918I01026",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "144055",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "BAJAJ FINSERV LTD.",
        "series": "EQ",
        "stockID": "822285",
        "strkPrice": "-1",
        "symbolName": "BAJAJFINSV",
        "token": "16675",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "62224",
        "sector": "Finance",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 23,
        "marketCap": "1215780.44",
        "tradeSymbol": "HDFCBANK-EQ",
        "isCashWithFno": true,
        "nseCashToken": "1333",
        "bseCashToken": "500180",
        "curFutToken": "",
        "astCls": "cash",
        "details": "HDFC BANK LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "156215",
        "instName": "",
        "isinCode": "INE040A01034",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "127815",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "HDFC BANK LTD",
        "series": "EQ",
        "stockID": "592009",
        "strkPrice": "-1",
        "symbolName": "HDFCBANK",
        "token": "1333",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "68314",
        "sector": "Banks",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 24,
        "marketCap": "356562.84",
        "tradeSymbol": "KOTAKBANK-EQ",
        "isCashWithFno": true,
        "nseCashToken": "1922",
        "bseCashToken": "500247",
        "curFutToken": "",
        "astCls": "cash",
        "details": "KOTAK MAHINDRA BANK LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "187740",
        "instName": "",
        "isinCode": "INE237A01028",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "153610",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "KOTAK MAHINDRA BANK LTD",
        "series": "EQ",
        "stockID": "621403",
        "strkPrice": "-1",
        "symbolName": "KOTAKBANK",
        "token": "1922",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "57638",
        "sector": "Banks",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 25,
        "marketCap": "373868.30",
        "tradeSymbol": "LT-EQ",
        "isCashWithFno": true,
        "nseCashToken": "11483",
        "bseCashToken": "500510",
        "curFutToken": "",
        "astCls": "cash",
        "details": "LARSEN & TOUBRO LTD.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "385705",
        "instName": "",
        "isinCode": "INE018A01030",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "315580",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "LARSEN & TOUBRO LTD.",
        "series": "EQ",
        "stockID": "837957",
        "strkPrice": "-1",
        "symbolName": "LT",
        "token": "11483",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "27490",
        "sector": "Infrastructure Developers & Operators",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 26,
        "marketCap": "267281.34",
        "tradeSymbol": "TITAN-EQ",
        "isCashWithFno": true,
        "nseCashToken": "3506",
        "bseCashToken": "500114",
        "curFutToken": "",
        "astCls": "cash",
        "details": "TITAN COMPANY LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "401920",
        "instName": "",
        "isinCode": "INE280A01028",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "328850",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "TITAN COMPANY LIMITED",
        "series": "EQ",
        "stockID": "372338",
        "strkPrice": "-1",
        "symbolName": "TITAN",
        "token": "3506",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "26633",
        "sector": "Diamond, Gems and Jewellery",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 27,
        "marketCap": "1743665.80",
        "tradeSymbol": "RELIANCE-EQ",
        "isCashWithFno": true,
        "nseCashToken": "2885",
        "bseCashToken": "500325",
        "curFutToken": "",
        "astCls": "cash",
        "details": "RELIANCE INDUSTRIES LTD",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "326840",
        "instName": "",
        "isinCode": "INE002A01018",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "267420",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "RELIANCE INDUSTRIES LTD",
        "series": "EQ",
        "stockID": "605152",
        "strkPrice": "-1",
        "symbolName": "RELIANCE",
        "token": "2885",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "27062",
        "sector": "Refineries",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 29,
        "marketCap": "595174.96",
        "tradeSymbol": "HINDUNILVR-EQ",
        "isCashWithFno": true,
        "nseCashToken": "1394",
        "bseCashToken": "500696",
        "curFutToken": "",
        "astCls": "cash",
        "details": "HINDUSTAN UNILEVER LTD.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "264580",
        "instName": "",
        "isinCode": "INE030A01027",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "216480",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "HINDUSTAN UNILEVER LTD.",
        "series": "EQ",
        "stockID": "779011",
        "strkPrice": "-1",
        "symbolName": "HINDUNILVR",
        "token": "1394",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "39943",
        "sector": "FMCG",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 30,
        "marketCap": "307192.68",
        "tradeSymbol": "ASIANPAINT-EQ",
        "isCashWithFno": true,
        "nseCashToken": "236",
        "bseCashToken": "500820",
        "curFutToken": "",
        "astCls": "cash",
        "details": "ASIAN PAINTS LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "314550",
        "instName": "",
        "isinCode": "INE021A01026",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "257360",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "ASIAN PAINTS LIMITED",
        "series": "EQ",
        "stockID": "244442",
        "strkPrice": "-1",
        "symbolName": "ASIANPAINT",
        "token": "236",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "34531",
        "sector": "Paints/Varnish",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 31,
        "marketCap": "1262317.84",
        "tradeSymbol": "TCS-EQ",
        "isCashWithFno": true,
        "nseCashToken": "11536",
        "bseCashToken": "532540",
        "curFutToken": "",
        "astCls": "cash",
        "details": "TATA CONSULTANCY SERV LT",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "451480",
        "instName": "",
        "isinCode": "INE467B01029",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "369400",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "TATA CONSULTANCY SERV LT",
        "series": "EQ",
        "stockID": "513374",
        "strkPrice": "-1",
        "symbolName": "TCS",
        "token": "11536",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "21708",
        "sector": "IT - Software",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 32,
        "marketCap": "279984.28",
        "tradeSymbol": "ADANIENT-EQ",
        "isCashWithFno": true,
        "nseCashToken": "25",
        "bseCashToken": "512599",
        "curFutToken": "",
        "astCls": "cash",
        "details": "ADANI ENTERPRISES LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "363250",
        "instName": "",
        "isinCode": "INE423A01024",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "297210",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "ADANI ENTERPRISES LIMITED",
        "series": "EQ",
        "stockID": "789039",
        "strkPrice": "-1",
        "symbolName": "ADANIENT",
        "token": "25",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "29640",
        "sector": "Trading",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 33,
        "marketCap": "424893.26",
        "tradeSymbol": "BAJFINANCE-EQ",
        "isCashWithFno": true,
        "nseCashToken": "317",
        "bseCashToken": "500034",
        "curFutToken": "",
        "astCls": "cash",
        "details": "BAJAJ FINANCE LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "721185",
        "instName": "",
        "isinCode": "INE296A01024",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "590065",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "BAJAJ FINANCE LIMITED",
        "series": "EQ",
        "stockID": "959222",
        "strkPrice": "-1",
        "symbolName": "BAJFINANCE",
        "token": "317",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "14832",
        "sector": "Finance",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 34,
        "marketCap": "281588.40",
        "tradeSymbol": "MARUTI-EQ",
        "isCashWithFno": true,
        "nseCashToken": "10999",
        "bseCashToken": "532500",
        "curFutToken": "",
        "astCls": "cash",
        "details": "MARUTI SUZUKI INDIA LTD.",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "1265070",
        "instName": "",
        "isinCode": "INE585B01010",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "1035060",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "MARUTI SUZUKI INDIA LTD.",
        "series": "EQ",
        "stockID": "984862",
        "strkPrice": "-1",
        "symbolName": "MARUTI",
        "token": "10999",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "8488",
        "sector": "Automobile",
        "marketCapCategory": "Large Cap"
    },
    {
        "scripOrder": 35,
        "marketCap": "211145.60",
        "tradeSymbol": "NESTLEIND-EQ",
        "isCashWithFno": true,
        "nseCashToken": "17963",
        "bseCashToken": "500790",
        "curFutToken": "",
        "astCls": "cash",
        "details": "NESTLE INDIA LIMITED",
        "divider": "100",
        "exchName": "NSE",
        "expirydate": "01 Jan 1980",
        "highPrice": "285855",
        "instName": "",
        "isinCode": "INE239A01024",
        "lotMult": "1",
        "lotSize": "",
        "lowPrice": "233885",
        "minLot": "1",
        "mktSegID": "1",
        "optType": "",
        "precsn": "2",
        "priceTck": "0.05",
        "regLot": "1",
        "secDesc": "NESTLE INDIA LIMITED",
        "series": "EQ",
        "stockID": "226036",
        "strkPrice": "-1",
        "symbolName": "NESTLEIND",
        "token": "17963",
        "npriceNum": "1",
        "npriceDen": "1",
        "holdQty": 0,
        "baseQty": 0,
        "total_qty": 0,
        "baseAvgPrice": 0,
        "avgPrice": 0,
        "dbq": 0,
        "dsq": 0,
        "dbap": 0,
        "dsap": 0,
        "dpholding": 0,
        "invested": 0,
        "isCommodityWithOption": false,
        "isIndices": false,
        "maxSingleTransactionQty": "37602",
        "sector": "FMCG",
        "marketCapCategory": "Large Cap"
    }
]